import '../vendor/assets/plugins/bootstrap/css/bootstrap.min.css'
import '../vendor/css/all_icons.css'
import '../vendor/css/loader.css'
import '../vendor/assets/plugins/metisMenu/metisMenu.min.css'
import 'material-icons/iconfont/material-icons.css'


import '../vendor/css/kavach.min.css'
import '../vendor/css/animate.css'
import '../vendor/css/skin/green-skin.css'
import 'jquery/src/jquery'
import '../../node_modules/bootstrap/dist/js/bootstrap.min'
import '../vendor/assets/plugins/metisMenu/metisMenu.min'
import '../vendor/assets/plugins/slim-scroll/js/jquery.slimscroll'
import '../vendor/js/loader'
import '../vendor/js/kavach.min'